name: Deploy Backend - AWS Lambda

on:
    push:
        branches:
            - main
        paths:
            - 'backend/*'
            - 'backend/**'
            - '.github/workflows/backend-deploy.yml'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup python 3.11
              uses: actions/setup-python@v4
              with:
                    python-version: 3.11
            
            - name: Setup Docker
              uses: docker/setup-buildx-action@v3

            - name: Instal cdk and Python dependencies
              run: |
                pip install aws-cdk-lib constructs
                cd cdk
                pip install -r requirements.txt || true

            - name: Setup AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ${{ secrets.AWS_REGION }}
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                role-duration-seconds: 1200
                role-session-name: github-actions

            - name: CDK Deploy
              run: |
                cd cdk
                cdk deploy --require-approval never
              env:
                CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
                CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
                FE_BUCKET_NAME: ${{ secrets.FE_BUCKET_NAME }}

