name: Deploy Frontend - AWS S3 + CloudFront
on:
    push:
        branches:
            - main
        paths:
            - 'frontend/*'
            - 'frontend/**'
            - '.github/workflows/frontend-deploy.yml'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: setup nodejs
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
                cache: 'npm'

            - name: Install dependencies
              run: |
                cd frontend
                npm install
                npm install -g aws-cdk

            - name: Build app
              run: |
                cd frontend
                npm run build

            - name: Setup AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ${{ secrets.AWS_REGION }}
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                role-duration-seconds: 1200
                role-session-name: github-actions
            
            - name: Sync to S3
              run: |
                cd frontend
                aws s3 sync ./dist s3://${{ secrets.FE_BUCKET_NAME }} --delete --region ${{ secrets.AWS_REGION }}